# Generated by Django 4.1.3 on 2022-11-16 12:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_alter_customuser_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser',
            name='id',
            field=models.IntegerField(auto_created=True, blank=True, primary_key=True, serialize=False),
        ),
    ]
