# Generated by Django 4.1.3 on 2022-11-22 07:33

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='TodoItem',
            fields=[
                ('id', models.IntegerField(blank=True, primary_key=True, serialize=False, verbose_name='id')),
                ('title', models.TextField(max_length=255, verbose_name='title')),
                ('description', models.TextField(max_length=255, verbose_name='description')),
                ('done', models.BooleanField(default=False, verbose_name='done')),
            ],
            options={
                'verbose_name': 'item',
                'verbose_name_plural': 'items',
            },
        ),
        migrations.CreateModel(
            name='TodoList',
            fields=[
                ('id', models.IntegerField(blank=True, primary_key=True, serialize=False, verbose_name='id')),
                ('title', models.TextField(max_length=255, verbose_name='title')),
                ('description', models.TextField(max_length=255, verbose_name='description')),
            ],
            options={
                'verbose_name': 'TodoList',
                'verbose_name_plural': 'TodoLists',
            },
        ),
        migrations.CreateModel(
            name='UsersLists',
            fields=[
                ('id', models.IntegerField(blank=True, primary_key=True, serialize=False, verbose_name='id')),
                ('list_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='todo.todolist')),
                ('user_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'UsersList',
                'verbose_name_plural': 'UsersLists',
            },
        ),
        migrations.CreateModel(
            name='ListItems',
            fields=[
                ('id', models.IntegerField(blank=True, primary_key=True, serialize=False, verbose_name='id')),
                ('item_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='todo.todoitem')),
                ('list_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='todo.todolist')),
            ],
            options={
                'verbose_name': 'ListItem',
                'verbose_name_plural': 'ListItems',
            },
        ),
    ]
