# Generated by Django 4.1.3 on 2023-03-09 18:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('todo', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='listitems',
            old_name='item_id',
            new_name='item',
        ),
        migrations.RenameField(
            model_name='listitems',
            old_name='list_id',
            new_name='list',
        ),
        migrations.RenameField(
            model_name='userslists',
            old_name='list_id',
            new_name='list',
        ),
        migrations.RenameField(
            model_name='userslists',
            old_name='user_id',
            new_name='user',
        ),
    ]
